### ISSUE TITLE
Future Roadmap Suggestions

### ISSUE THREAD

**Issue by RogerChern** [TuSimple/simpledet#66]
- Rewrite proposal generation from CUDA to Python
Thanks to https://github.com/apache/incubator-mxnet/pull/14363, MXNet CustomOp now works parallelly. This enables us to migrate more CUDA codes to Python to ease the modification of core operators.

**Comment by RogerChern** [comment]
- [x] Fix RoiAlignv2 compilation failure introduced by https://github.com/apache/incubator-mxnet/pull/14270

**Comment by RogerChern** [comment]
- [ ] TVM deployment

**Comment by RogerChern** [comment]
- [ ] multi-node sync bn

**Comment by RogerChern** [comment]
- [ ] horovod distributed training

**Comment by RogerChern** [comment]
- [ ] speedup loader with https://github.com/apache/incubator-mxnet/pull/14733

**Comment by feixiangdekaka** [comment]
>     * [ ]  speedup loader with [apache/incubator-mxnet#14733](https://github.com/apache/incubator-mxnet/pull/1473

~/anaconda3/envs/simpledet/simpledet$ python3 detection_test.py --config config/faster_r50v1c4_c5_512roi_1x.py 
total number of images: 5000
load experiments/faster_r50v1c4_c5_512roi_1x/checkpoint-0006.params
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/anaconda3/envs/simpledet/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/envs/simpledet/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "detection_test.py", line 79, in eval_worker
    out = [x.asnumpy() for x in exe.get_outputs()]
  File "detection_test.py", line 79, in <listcomp>
    out = [x.asnumpy() for x in exe.get_outputs()]
  File "/home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1996, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:15:08] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)
Stack trace:
  [bt] (0) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x34) [0x7f1882a542f4]
  [bt] (1) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::GAPOp<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x373) [0x7f18863b16b3]
  [bt] (2) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x2dc) [0x7f18843099ec]
  [bt] (3) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x79) [0x7f18842646e9]
  [bt] (4) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(+0x27a25be) [0x7f188421e5be]
  [bt] (5) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x5c4) [0x7f18848d97d4]
  [bt] (6) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0x11d) [0x7f18848ee5fd]
  [bt] (7) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>)+0x4e) [0x7f18848ee89e]
  [bt] (8) /home/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x4b) [0x7f18848d772b]

**Comment by suman-19** [comment]
Rotation Invariant Object Detection to train on DOTA dataset.

**Comment by RogerChern** [comment]
- [ ] Support NDArray and Symbol dual modes for user-friendly debug.

**Comment by RogerChern** [comment]
- [ ] refactor code with https://github.com/apache/incubator-mxnet/pull/14638

**Comment by RogerChern** [comment]
- [ ] refactor code https://github.com/apache/incubator-mxnet/pull/13985

**Comment by RogerChern** [comment]
- [ ] file corruption check for #182

**Comment by RogerChern** [comment]
- [ ] wrap the contrib RoIAlign for our use
Our one is written in quite an early day and is slightly different from the official Detectron implementation. Also, ours lacks FP16 support, sampling ratio, and PS variant.

**Comment by RogerChern** [comment]
pinning memory for loader

**Comment by xchani** [comment]
model parallelism with pipeline
